### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by splitice** [cstate/cstate#161] opened 2020-12-11 02:14 UTC
**Describe the bug**

If the component name has upper case (e.g `LAX1`) and the issue is created with incorrect case i.e `lax1` then the incident will display in the filtered list but not impact the current status.

Verified against latest master

**Comment by splitice** [comment] 2020-12-11 02:15
Yes the admin interface is clear that it should be the exact component (which if followed would prevent this issue).

There is probably a way to do a case insensitive slice?

**Comment by mistermantas** [comment] 2020-12-11 16:24
https://gohugo.io/content-management/taxonomies/

I’m sorry, but I think this is out of scope from my POV.

It is a hugo thing, not a cstate thing. I agree that this behavior is not ideal, but all I can do is post about it on a forum and edit the default config

**Comment by mistermantas** [comment] 2020-12-11 16:32
https://discourse.gohugo.io/c/support/34

**Comment by splitice** [comment] 2020-12-15 05:16
Personally I don't view this as correctly closed.


If hugo is case insensitive that's fine. You should be case-insensitive in your matching too. The inconsistency is the bug. Not the fact that hugo is case insensitive.

**Comment by mistermantas** [comment] 2020-12-15 18:36
The thing is I'm not sure if a) that can be changed and b) I understood correctly what you meant.

Everything works when you use the right caps. I wish the caps did not matter though.

**Comment by splitice** [comment] 2020-12-16 00:21
I'm honestly confused about how that slice works to be honest. I experimented and tried to change it but was unsuccesful. I didnt have much time or any hugo experience though.

There are a few examples of it but this is an example line that needs to be insensitive to get consistency: https://github.com/cstate/cstate/blob/master/layouts/partials/index/components.html#L55

**Comment by mistermantas** [comment] 2020-12-16 19:09
This code i believe is used in many places

https://discourse.gohugo.io/t/where-function-with-case-insensitive-and-reverse-match/22317

I will check back sometime later. Contributions encouraged

**Comment by mistermantas** [comment] 2021-02-24 15:06
Apologies for closing this issue earlier. I have now reproduced it and I'm looking to [fix it with the help of some hugo folk](https://discourse.gohugo.io/t/ignore-case-sensitivity-where-slice-force-caps-sensitivity-for-taxonomies/31417) before the next release.

**Comment by mistermantas** [comment] 2021-03-05 20:59
I've been trying to fix this for definitely at least an hour with the example a forum mod gave me, but it's not working with the way that hugo filters active issues for a specific system (component)

There's a workaround I'll mention which is defining all your systems in lowercase (in `name`) and using `displayName` to show the correct case.

Is it perfect? no... but the current hugo templates don't support a reasonable way to 'equalize' the capitalization

I got this code working only to realize it doesn't do the thing I need it to. 

``` 
        {{ range $active }} 
          {{ $allAffectedSystemsLowercaseRange := apply .Params.affected "lower" "." }}
          {{ $part := delimit $allAffectedSystemsLowercaseRange " " }} 
          {{ $.Scratch.Add "allAffectedSystemsLowercaseString" $part }}
        {{ end }}
        {{ $allAffectedComponents := $.Scratch.Get "allAffectedSystemsLowercaseString" }}
        {{ $.Scratch.Set "allAffectedSystemsLowercaseString" "" }}
 ```

In essence, what I'd have to do is:

1. lowercase all the system names in an active issue
2. lowercase the name of the category (which is easy)
3. check whether those match

I can't do #1 because when I lowercase everything I lose the context of the issue (i.e. the status: is it a disruption or just a notice?), therefore I can't move further at the moment.

I am going to try one last thing and if it doesn't work, then this bug won't be fixed in v5

**Comment by mistermantas** [comment] 2021-03-05 21:09
I guess I spoke too soon.

🥇 I GOT THIS WORKING yay 🥳 🎉 

at the cost of _some_ spaghetti code (twice or thrice more lines):

```

        {{ $caseInsensitiveSystemName := lower .name }}
 
        
        <!-- Notice categories  -->
        {{ range $isNotice }} 
          {{ $allNoticeSystemsLowercaseRange := apply .Params.affected "lower" "." }}
          {{ $part := delimit $allNoticeSystemsLowercaseRange " " }} 
          {{ $.Scratch.Add "allNoticeSystemsLowercaseString" $part }}
        {{ end }}
        {{ $allNoticeComponents := $.Scratch.Get "allNoticeSystemsLowercaseString" }}
        {{ $.Scratch.Set "allNoticeSystemsLowercaseString" "" }}

        <!-- Disrupted categories  -->
        {{ range $isDisrupted }} 
          {{ $allDisruptedSystemsLowercaseRange := apply .Params.affected "lower" "." }}
          {{ $part := delimit $allDisruptedSystemsLowercaseRange " " }} 
          {{ $.Scratch.Add "allDisruptedSystemsLowercaseString" $part }}
        {{ end }}
        {{ $allDisruptedComponents := $.Scratch.Get "allDisruptedSystemsLowercaseString" }}
        {{ $.Scratch.Set "allDisruptedSystemsLowercaseString" "" }} 
        
        <!-- Down categories  -->
        {{ range $isDown }} 
          {{ $allDownSystemsLowercaseRange := apply .Params.affected "lower" "." }}
          {{ $part := delimit $allDownSystemsLowercaseRange " " }} 
          {{ $.Scratch.Add "allDownSystemsLowercaseString" $part }}
        {{ end }}
        {{ $allDownComponents := $.Scratch.Get "allDownSystemsLowercaseString" }}
        {{ $.Scratch.Set "allDownSystemsLowercaseString" "" }} 
 
        
        <!-- Now finally check -->
        {{ $thisIsNotice := in $allNoticeComponents $caseInsensitiveSystemName }}
        {{ $thisIsDisrupted := in $allDisruptedComponents $caseInsensitiveSystemName }}
        {{ $thisIsDown := in $allDownComponents $caseInsensitiveSystemName }}
```

**Closed by mistermantas** 2021-03-05 21:09 UTC
Labels: bug, discussion, help wanted

**Comment by mistermantas** [comment] 2021-03-05 21:15
Update: My solution is half working. It does not work for the API, so because of that it's kind of unusable. This... might not actually be possible to achieve properly.
