### ISSUE TITLE
Broken links if baseURL contains non-root path

### ISSUE THREAD

**Issue by zeeZ** [cstate/cstate#126] opened 2020-08-07 15:11 UTC
**Describe the bug**
With a config such as `baseURL: http://example.com/foo/` several links are broken because they begin with `/`.

**Reproduction steps**
1. `cd exampleSite && hugo serve --baseUrl=http://localhost/cstate/ --theme=cstate --themesDir=../.. --verbose`
2. Open `http://localhost:1313/cstate/` in browser
3. Notice broken site logo, clicking on the `api` tag inside the notice box or any of the system names results in a 404

**Expected behavior**
Links should not be broken, cstate should work when hosted in a subdirectory where the root is not available.

I *think* this is a relatively easy fix by piping links that begin with a `/` into `relURL`. I've made some local changes that seem to work, but I'm nowhere near an expert on Hugo.

**Comment by mistermantas** [comment] 2020-08-07 15:37
I noticed this when I tried setting up GitLab Pages but thought it was something with GitLab, not cState.

Thanks, I'll look into this.

**Comment by zeeZ** [comment] 2020-08-07 15:50
I basically went through an replaced a few things with `{{ printf "/affected/%s/" (. | urlize) | relURL }}` and similar. I can open a PR with what I have if you'd like.

**Comment by mistermantas** [comment] 2020-08-07 15:53
Not sure why but `{{ printf "/affected/%s/" (. | urlize) | relURL }}` looks super hacky. There HAS to be a way to do this without printf.

I can't push this today, but I tried figuring out what might be causing the problem:

- Some links just simply are "/" so they go to the root. (like in header.html partial)
- Logo, by default, is listed as "/logo.png" so removing the slash here is all you need to do.
- Most links just need the "/" at the start removed, I think, so as per your example (`/affected/...` => `affected/...`):

```html


        <p><small>
          {{ range .Params.Affected }}
            <a href="/affected/{{ . | urlize }}/" class="tag no-underline">{{ . }}</a>
          {{ end }}
        </small></p>
```
from https://github.com/cstate/cstate/blob/master/layouts/partials/index/announcements.html

**Comment by zeeZ** [comment] 2020-08-07 16:38
Here's the changes I had originally made: https://github.com/zeeZ/cstate/commit/e8cefd26672ca8468f42420965f9d44899ae0304
But you're right, this seems much simpler, though I don't know if that works everywhere: https://github.com/zeeZ/cstate/commit/fa55bc541e9b26e12f2bc67f83c3860c3233052f

Luckily the page that uses pagination (which adds `page/2` to the URL) uses permalinks, so no issues there.

There are some `/admin` paths in  `partials/js.html` for Netlify I wasn't sure about.

**Comment by mistermantas** [comment] 2020-08-11 10:22
I'll close this as I've implemented the basic bug fixes you outlined in your changes as well (which just involved removing the `/` slash in template URLs).

Please let me know if there are any other issues!

**Comment by zeeZ** [comment] 2020-08-11 11:06
The current change on dev has two issues:
  - clicking the component tag on individual issue view (`issues/2019-10-testing-new-pipeline/`) 404s because it tries to go to `issues/2019-10-testing-new-pipeline/affected/api/` -> change `issues/issue.html` to `../../affected`?
  - since the header partial is included in the 404 page it can appear in any subpath, so I don't believe there's a way around calling `relURL` for the logo. For example `affected/backup-gateway/` has no content and the logo would end up pointing to `affected/backup-gateway/logo.png`

**Comment by mistermantas** [comment] 2020-08-11 18:08
Thank you for bringing them up.

**Comment by zeeZ** [comment] 2020-08-12 12:29
I've set up GitLab to mirror this repository and push the `dev` branch to pages for the time being: https://kurisuchan.gitlab.io/cstate/

Clicking on **API** on [issues/2019-10-08-testing-new-pipeline](https://kurisuchan.gitlab.io/cstate/issues/2019-10-08-testing-new-pipeline/) takes you to `issues/2019-10-08-testing-new-pipeline/affected/api/` instead of `affected/api`. 

That seems to be the only thing left that I can see. The [error page](https://kurisuchan.gitlab.io/cstate/affected/backup-gateway/) looks good now, even for subdirectories.

**Comment by mistermantas** [comment] 2020-08-12 13:10
Yes, I haven't set up the last bits yet. It's why the issue is still open
:) Thank you for the gitlab link!

**Comment by mistermantas** [comment] 2020-08-12 17:36
I ended up going with your solutions for most of these. I hope that cState'll work with non-root paths fully in the future -- this is why the support was extended to Netlify CMS as well in #127

**Closed by mistermantas** 2020-08-12 17:36 UTC
Labels: bug, priority: high
